### ISSUE TITLE
[RFC] Forms - INNO-1419

### ISSUE THREAD

**Issue by emeryro** [ec-europa/europa-component-library#1057] opened 2019-03-28 13:36 UTC
# Forms elements and groups

## Current situation

- 4 forms components available (`select`, `text-area`, `text-input`, `radio`)
- all form components are wrapped into a "container", and displays optionnal label, helper text and invalid text
  - label is based on `ecl-form-label`
  - helper text is based on `ecl-help-block`
  - invalid text is based on `ecl-feedback-message`
  - `select`, `text-area` and `text-input` are wrapped into a `ecl-form-group`, `radio` is wrapped into a `ecl-radio__group` (see below why) 
- form components will be redesign soon (mainly the invalid state). `radio` is the first one with the new design.

Note: `search-form` component has been excluded from the analysis as it is not intended to be used along other form elements

## Issues

There are mainly two issues here:

### Issue 1: Extra classes

As every ECL component, form components allows to add extra classes and attributes.
But for `select`, `text-area` and `text-input` these extra classes are put on the form element itself, and not on the wrapper. 
**Pseudo code:**
```
<wrapper>
  <label>Label</label>
  <formElement class="extra-class" />
</wrapper>
```
**React:**
![image](https://user-images.githubusercontent.com/25579221/55160155-f9bbf380-5162-11e9-96d3-e656baa5dab1.png)
As a consequence, it isn't possible for instance to add extra margin before or after a form component; margin would be added to the form element (so between the form element and the label in the pseudo code ahead)
![image](https://user-images.githubusercontent.com/25579221/55220680-152d0a00-5208-11e9-86bd-74d3800ba11a.png)

### Issue 2: The case of ecl-form-group

The main role of `ecl-form-group` is to add extra margin inside a form component (between label and form element for instance).
The issue is that it comes with high specificity rule that may override component's rules (see below)
![image](https://user-images.githubusercontent.com/25579221/55154742-e22a3e00-5155-11e9-8e38-d052f03b5a07.png)

That's the reason why it hasn't been used in radio group (spacing between elements isn't always the same). Spacing have been added directly into the component.

Still concerning ecl-form-group, there are also some inconsitencies in class names:
Some forms classes are prefixed with `form` (ecl-form-group, ecl-form-label), some other are not (ecl-help-block, ecl-feedback-message).
As far as I know, all these classes are used only in forms (component `ecl-message` do not use `ecl-feedback-message` for instance)

### Extra classes

**Option A1: Add an additional parameter at group level**
So integrators would have the possibility to add extra classes around the component, or on the form elment itself
```
<wrapper class="extra-class-wrapper">
  <label>Label</label>
  <formElement class="extra-class" />
</wrapper>
```

**Option A2: Move custom classes to group level**
As the form component is nested inside the group, having a class at top level isenough to apply any required styling on the form element
```
<wrapper class="extra-class">
  <label>Label</label>
  <formElement />
</wrapper>
```

### Form group

**Option B1: Get rid of these common form classes and define what we need into components (as done in `radio`)**
It would probably induce some (small) duplicate in the code, but would give us more flexibility.

**Option B2: Update the common classes to make them less intrusive and more consistent**
It may make sense for instance to have the invalid display in it too (the red border), as it should be the same for every form components

**Comment by emeryro** [comment] 2019-03-28 13:59
I personally would go for options A2 and B1

**Comment by kalinchernev** [comment] 2019-03-29 09:38
Thanks for making a good point about several issues at the some time!

For me, it seems one of the main issues is the inconsistency, although it's clearly not the only issue at hand with forms.

I'm not very experienced with RFC, but it feels that probably the issue would need a split of categories, as together with clear inconsistencies, there are other two bigger questions.

On the points:

1) **Extra classes** - probably the easiest one - each component should have the ability to apply extra classes. As far as I know, that's a very old and fundamental rule together with the rule that there should be no spacing rules on top-level elements (wrappers)

2) **The form group** - doesn't feel like a component on first place. It's more of a glue between other components. Maybe it's more of a utility, or it should yield it's rules to the sub-components it's changing.

I don't have a strong suggestion at this stage, only thoughts that it's not fitting well into the category of being a component and probably that's why it's also not consistent with the others.

3) **Class naming** - good point as well. I think this could be also split into another topic which is following up the conclusions of the form group. If components/elements are not used only in forms, then it's clear it's not needed to refactor. Not sure, but messages are probably a candidate for a separate component if not already.

**Comment by planctus** [comment] 2019-03-29 10:26
Quick opinion is that assigning extra_classes to a wrapper seems more effective than doing it on the "input" tag, as long as we have a consistent way of applying a container to all the form elements which doesn't seem to be the case at the moment

- text field and text area use the form-group as the wrapper 
- radio and select have their own wrapper

I also see that in some cases the input is an element of the component, sometimes is the component itself: the select element is "ecl-select", radio is "ecl-radio__input".

Regarding the form-group i think we should identify which are the use cases we need and we want to support, a kind of overall layout for a complex form with multiple elements defining things that are relative to the form but not part of any input, like fieldset, legends.
In the info styleguide we did this, not saying it's a good example but it gives basically all the "supported" solutions for building forms using the styleguide and yes, we call it "form group" :)
This is, at the moment, what you can do with forms in the info family websites.
https://ec-europa.github.io/digital-transformation-dev/section-form.html

**Comment by yhuard** [comment] 2019-04-01 13:57
The issue is not only about CSS classes, but about all the HTML attributes in general. There are cases where one might want to add a `data-*` attribute on the wrapper, or on the input, or on both. Ideally, every HTML element should be customizable. In practice, we sometimes use tags to wrap others for styling purpose only. Should these tags be customizable as well? Or should only the main, meaningful tags be exposed?

There's also the question of how to structure the information in a complex environment like a form...

(to be continued)

**Comment by yhuard** [comment] 2019-04-08 13:50
We should try to separate form controls (or fields) and form groups (including fieldsets). We could event add a third group: form actions (buttons)

## Form controls

Composed by: 
- label (mandatory, can be visually hidden)
- input (mandatory)
- helper text (optional)
- error message (optional)

Forms controls include:
- text input, text area
- select
- checkbox
- radio (edge case: doesn't contain error messages)

## Form groups

Most of the time a `fieldset`, but could also be a `div` if we don't have a `legend` (i.e. if the group has no "label").

Composed by: 
- form fields and/or other form groups (mandatory)
- legend (optional)
- helper text (optional)
- error message (optional)

Main components: 
- form group (`div`): visually but not semantically related fields
- `fieldset`s: semantically related fields

Sub-components:
- radio groups: group of related radios (extends `fieldset`)
- checkbox groups: group of related checkbox (same `name` attribute) (extends `fieldset`)

There could be questions about spacing and nesting or state management if the error is on the group or on the form field).

Another question: should we consider the form input + form action pattern here? (e.g. search)

## Form actions

How to display buttons. Aligned left? Right? "Cancel + Submit" or "Submit + Cancel"?

## Other thoughts

Should we have a `Form` component as well? Which would manage spacing between the aforementioned elements.

**Comment by emeryro** [comment] 2019-04-09 12:51
Things are going forward here, thanks
If I try to summarize/add my proposals:

# Form control

This is basically the form components we have now.
They should all allow custom classes and attributes at top level, and should define their inner elements (no more `ecl-form-label` or `ecl-help-block` for instance)

```
<div class="ecl-{control} + extra-class">
  <label class="ecl-{control}__label">Label</label>
  <input />
  <p class="ecl-{control}__help">Help text</p>
  <p class="ecl-{control}__invalid">Error message</p>
</div>
```
Depending on the control we may need an additional container (select for instance), but that won't change the global structure.

# Form group

That's a little more tricky.
I don't think we should differentiate several kind of groups ("standard" groups, radio groups, fieldsets, ...).

If several controls should be grouped, we put them in a form group (whatever it is). Every control will have its own data, so if they have the same name, they are related, but no need to have a specific form group for that.
The only thing that may vary is the spacing between controls (for radio buttons for instance they may be a little closer if they belong to the same group). But that could be solved with a variant of form group (it's just a css difference)

Each form group should also allow custom classes and attributes

```
<fieldset class="ecl-form-group + extra-class">
  <legend class="ecl-form-group__legend">Legend</legend>
  <p class="ecl-form-group__help">Help text</p>
  <p class="ecl-form-group__invalid">Error message</p>
  <formControl class="ecl-form-group__control" />
  <formControl class="ecl-form-group__control" />
   ...
</fieldset >
```

Note: `<fieldset>` may cause issues for styling, so we may have to use `<div>` and aria-attributes instead

# Other elements

`form action` and `form` may be useful sometimes, but I'll keep them for later, if needed. Result can be achieved with utilities and button variant for now.

**Comment by yhuard** [comment] 2019-04-16 12:53
> The only thing that may vary is the spacing between controls (for radio buttons for instance they may be a little closer if they belong to the same group). But that could be solved with a variant of form group (it's just a css difference)

Agree. For special cases, like radio groups or related checkboxes groups, we could use a condensed spacing to show they are related.

> Note: <fieldset> may cause issues for styling, so we may have to use <div> and aria-attributes instead

or we inject a blank `div` :° 

> Result can be achieved with utilities and button variant for now.

Where would you put usage guidelines for how to use buttons in a form?

**Comment by yhuard** [comment] 2019-04-23 12:43
https://auth0-cosmos.now.sh/docs/#/component/form

```
Form.Field
Form.Actions
Form.FieldSet
```

👼

**Comment by yhuard** [comment] 2019-04-30 06:51
https://veritas.udacity.design/#!/FormFieldset + https://veritas.udacity.design/#!/CheckboxGroup + https://veritas.udacity.design/#!/RadioGroup 😉

**Comment by yhuard** [comment] 2019-04-30 10:16
Let's close this issue and only use the PR https://github.com/ec-europa/europa-component-library/pull/1078 from now ;)

**Closed as completed by yhuard** 2019-04-30 10:16 UTC
Labels: RFC
